clpsite/clpsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('players/', include('players.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/players/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clpsite/players/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^players/$', views.PlayerListView.as_view(), name='players'),
        url(r'^player/(?P<pk>[0-9A-Za-z-]+)/$', views.PlayerDetailView.as_view(), name='player-detail'),
        ]
urlpatterns += [
        url(r'^agents/$', views.AgentListView.as_view(), name='agents'),
        url(r'^agent/(?P<pk>[0-9A-Za-z-]+)/$', views.AgentDetailView.as_view(), name='agent-detail'),
        url(r'^maps/$', views.MapListView.as_view(), name='maps'),
        url(r'^map/(?P<pk>[0-9A-Za-z-]+)/$', views.MapDetailView.as_view(), name='map-detail'),
        ]
urlpatterns +=[
        url('upload_image/',views.upload_image, name='upload_image'),
        ]

clpsite/players/models.py
from django.db import models
from django.urls import reverse
import uuid


class Image(models.Model):
    image = models.ImageField(upload_to = 'images')
    name = models.CharField(max_length=200)

class Country(models.Model):
    id= models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this country')
    name = models.CharField(max_length=200,help_text="Enter a country name")

    def __str__(self):
        return self.name

class Person(models.Model):
    id= models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this person')
    fullname= models.CharField(max_length=30, help_text="Enter a player fullname")
    birthday= models.DateField  (null=True, blank=True)
    country= models.ForeignKey('Country', on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=5000, help_text="Enter a person description",blank=True,null=True)
    image = models.ImageField(upload_to = 'images', blank=True)
    def __str__(self):
        return self.fullname

    @property
    def get_image_url(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Agent(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this setup')
    name = models.CharField(max_length=20, help_text="Enter a agent name")
    rol = models.ForeignKey('Rol',on_delete=models.SET_NULL, null=True, help_text="Select a rol for this Agent")
    icon = models.ImageField(upload_to = 'images', blank=True) 
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('agent-detail',args=[str(self.id)])

    @property
    def get_icon_url(self):
        try:
            url = self.icon.url
        except:
            url = ''
        return url



class Player(Person):
    nick = models.CharField(max_length=25, help_text="Enter a player nick")
    played_hours = models.IntegerField()
    rank = models.ForeignKey('Rank', on_delete=models.SET_NULL, blank= True, null=True) 
    agents = models.ManyToManyField('Agent',help_text="Enter a agents", blank=True)

    sensivility = models.FloatField(help_text="Enter a sens number",blank= True,null=True)
    dpi = models.IntegerField(help_text="Enter a dpi number",blank= True, null=True)

    monitor = models.CharField(max_length=50, help_text="Enter a monitor name",blank= True, null=True)
    mouse = models.CharField(max_length=50, help_text="Enter a mouse name",blank= True, null=True)
    mousepad = models.CharField(max_length=50, help_text="Enter a mousepad name",blank= True, null=True)
    keyboard = models.CharField(max_length=50, help_text="Enter a keyboard name",blank= True, null=True)
    headset = models.CharField(max_length=50, help_text="Enter a headset name",blank= True, null=True)
    


    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Player._meta.fields]


    def __str__(self):
        return self.nick
   
    def get_absolute_url(self):
        return reverse('player-detail',args=[str(self.id)])

class Rank(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this rank')
    name = models.CharField(max_length=20, help_text="Enter a rank name")
    image = models.ImageField(upload_to = 'images', blank = True)

    def __str__(self):
        return self.name

    @property
    def get_image_url(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Map(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this map')
    name = models.CharField(max_length=20, help_text="Enter a map name")
    image = models.ImageField(upload_to = 'images', blank=True)
    minimapa = models.ImageField(upload_to = 'images', blank=True)
    description = models.CharField(max_length=6000, help_text="Enter a map description", blank=True)
    tier_list = models.ManyToManyField('Tier', related_name="tier", help_text="Enter a tier", blank=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('map-detail',args=[str(self.id)])
    @property
    def get_image_url(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    @property
    def get_minimap_url(self):
        try:
            url = self.minimapa.url
        except:
            url = ''
        return url



class Rol(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this setup')
    name = models.CharField(max_length=20,help_text="Enter a rol name")
    def __str__(self):
        return self.name



class Tier(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this setup')
    name = models.CharField(max_length=20,help_text="Enter a name tier")
    agents = models.ManyToManyField('Agent', help_text="Enter a tier agent", blank=True)

    def __str__(self):
        return self.name

clpsite/players/forms.py
from django import forms
from .models import *

class ImageForm(forms.ModelForm):
   class Meta:
      model = Image
      fields = ['image','name']

clpsite/players/views.py
from django.shortcuts import render
from .models import Player, Country, Rank, Person, Agent, Map,Rol
from django.views import generic
from django.http import HttpResponseRedirect

def index(request):
    """ Funcion vista para la pagina de inicio del sitio"""
    num_players = Player.objects.all().count()
    num_maps = Map.objects.all().count() 
    num_agents = Agent.objects.all().count()

    return render(
            request,
            'index.html',
            context={'num_players':num_players,
            'num_maps':num_maps,
            'num_agents':num_agents})
   
class PlayerListView(generic.ListView):
    model = Player

class PlayerDetailView(generic.DetailView):
    model = Player

class MapListView(generic.ListView):
    model = Map

class MapDetailView(generic.DetailView):
    model = Map

class AgentListView(generic.ListView):
    model = Agent

class AgentDetailView(generic.DetailView):
    model = Agent


def upload_image(request):
    if request.method == 'GET':
        return render(request, 'upload_image.html')
    elif request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            new_image = Image(  image = form.cleaned_data["image"],
                                name = form.cleaned_data["name"]
                                )
            new_image.save()
            return HttpResponseRedirect('/players/upload_image/')

clpsite/players/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <!--  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Add additional CSS in static file -->
  <!-- {% load static %} -->
  <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
</head>


<body class="bg-dark">  
<h1 class="container-fluid display-1 p-5 bg-light text-center">Team CLP</h1>



<!-- NAVBAR INICIO-->

	<nav class="navbar navbar-expand-sm justify-content-center navbar-light  bg-secondary border-white border-5 ">
		<div class="container-fluid h1 ">	
		<ul class="navbar-nav ">	
					
					<li class="nav-items">
						<a class="nav-link  activate" href="{% url 'index' %}">Index</a>
					</li>
				        <li class="nav-item">
						<a class="nav-link " href="{% url 'players' %}">Players</a>
					</li>
				        <li class="nav-item">
						<a class="nav-link" href="{% url 'agents' %}">Agents</a>
					</li>
				        <li class="nav-item">
						<a class="nav-link " href="{% url 'maps' %}">Maps</a>
					</li>
		</ul>
		</div>
	</nav>
<!-- NAVBAR FIN -->

<div class="d-flex justify-content-center">
		<div class="col-sm-6 bg-danger pt-4">
 

      			{% block content %}{% endblock %}
      		</div>

</div>
  

</body>
</html>

clpsite/players/templates/index.html
{% extends "base_generic.html" %}


{%block title%}
	<title>Team Clp</title>
{% endblock %}


{% block content %}



<div class="container-fluid text-white text-center">
	<h1 class="display-1">Team CLP</h1>
	<p class="h5">Welcome to <em>Team Clp webpage</em></p>
 
	<h2> Team Info</h2>
  <p>The site has some data:</p>
  <ul class="display-6">
    <li><strong>Players: </strong> {{ num_players }}</li>
    <li><strong>Maps: </strong>{{num_maps}}</li>
    <li><strong>Agents:  </strong>{{num_agents}}</li>
  </ul>
</div>






{% endblock %}

clpsite/players/templates/players/agent_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1> {{ agent.name }} </h1>
	<p><strong>Clase : </strong>{{agent.rol}}</p>
{% endblock %}

clpsite/players/templates/players/agent_list.html
{% extends "base_generic.html"%}

{% block content %}

<div class="d-flex justify-content-center bg-dark text-white mb-1 border">
	<h1 class="display-1 h1 border-bottom mb-5">Agents</h1>

</div>
<<<<<<< HEAD
<div class="bg-danger">
<div class="container">
	{% if agent_list %}
        <ul class="row justify-content-center" style="padding-right: 20px">
                {% for agent in agent_list %}
		<a href="{{agent.get_absolute_url}}" class=" col-3 display-6 text-white text-center text-decoration-none">

                <li class=" bg-dark text-center border mt-4" style="list-style-type: none">
			<img src="{{ agent.get_icon_url }}" class="mx-auto bg-light border mt-5" width="100" height="100" > <p class="mb-5">{{ agent.name }}</p>
				</a>
		</li>
                {% endfor %}
        </ul>
        {% endif %}
</div>
</div>
<!--

	<h1 class="h1 display-1 text-center"> Agentes </h1>
	{% if agent_list %}
	<div class="card-group">
	{% for agent in agent_list %}
		<div class="card col-3">
			<img class="card-img-top" src="{{agent.get_icon_url}}">
			<div class=" card-body">
				<h5 class="card-title">{{agent.name}}</h5>
				<p class="card-text"> {{agent.rol }} </p>
			</div>

		</div>

	{% endfor%}
	</div>
	{% endif %}
-->
{% endblock %}
=======
>>>>>>> 5004f1b2dfb9c9717a0e4b5db6d79c09d677d3b2




 <div class="bg-danger">
          {% if agent_list %}
          <ul class="row justify-content-center">
                 {% for agent in agent_list %}
                                  <a  class=" col-sm-4 display-6 text-white text-center text-decoration-none mt-3" style="font-size: calc(1rem + 1vw)" href="{{agent.get_absolute_url}}">
 
                                  <li class=" bg-dark text-center border " style="list-style-type: none; height: calcu(12rem + 1vw) ">
					  <p class="px-3 "    > {{agent.name}} </p>
                                          <img src="{{ agent.get_icon_url }}" class="img-fluid mx-auto max-width:auto height:200px border border-white  mb-5" style="height:5em"> 
                  </li></a>
                  {% endfor %}
          </ul>
          {% endif %}
 </div>
  {% endblock %}

clpsite/players/templates/players/map_detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="d-flex justify-content-center bg-dark text-white mb-1">
<h1 class="display-1 h1 border-bottom mb-5">{{map.name}}</h1>

</div>

<!-- Info de la Persona -->


<div class="d-inline mb-5 bg-dark text-light mb-5 ">
<div class="d-flex bg-dark mb-4 ">

                <!-- Datos de la persona -->
                <div class="col-6 display-6 border-dark border text-center ">
               		<p class=" text-center">{{map.description}}</p>
		</div>

<!-- Fin Datos de la persona -->
<!-- Foto de perfil -->


                <div class="col-6 d-flex border border-dark justify-content-center align-content-center">

			<img src="{{ map.get_minimap_url }}" class="img-responsive" width="90%" height="10%" >
                </div>

</div>
<!-- Fin Foto de perfil -->







<!-- Fin Info de la Persona-->
<!--  Historia del Player -->

<div class="d-flex justify-content-center bg-dark text-white mb-1">
<h1 class="display-1 h1 border-bottom mb-5">Agent tier list</h1>

</div>

{%for tier in map.tier_list.all%}
<div class="d-inline mb-5 bg-black text-light mb-5 ">
<div class="d-flex  bg-dark">

	
	<div class="d-flex col-3 justify-content-center border border-right">
		<h1 class="display-3 h1 ">{{tier.name|slice:"-1:"}}</h1>
	</div>

	<div class="d-flex col-9  p-3 justify-content-around border">
         	 {% for agent in tier.agents.all %}
		  <a href="{{agent.get_absolute_url}}" class="link-info display-6 justify-content-around text-danger"> 

                                          <img src="{{ agent.get_icon_url }}" class="mx-auto thumbnail" width="50" heigth="50" > </a>
          {% endfor %}
              </div>
</div>

</div>
{% endfor %}
<!-- Fin Historia del Player -->
<!--  Pool de agentes  -->









{% endblock %}

clpsite/players/templates/players/map_list.html
{% extends "base_generic.html"%}

{% block content %}
<div class="d-flex justify-content-center bg-dark border text-white mb-1">
	<h1 class="display-1 h1 border-bottom mb-5 ">Maps</h1>
</div>
<!--
<div class="d-flex bg-warning mb-4 p-3">

        {% for map in map.list %}
        	<a href="{{map.get_absolute_url}}" class="link-info display-3 justify-content-around text-danger">
			<img src="{{ map.get_image_url }}" class="mx-auto thumbnail" width="100" heigth="100" > {{ map.name }}</a>
        {% endfor %}

</div>
-->






<div class="bg-danger">
        {% if map_list %}
        <ul class="row justify-content-center">
               {% for map in map_list %}
                                 <a  class=" col-sm-6 display-6 text-white text-center text-decoration-none mt-3" style="font-size: calc(1rem + 1vw)" href="{{map.get_absolute_url}}">
                                        <li class=" bg-dark text-center border " style="list-style-type: none; height: calcu(12rem + 1vw) ">
						<p class="px-3 "    > {{map.name}} </p>
					<img src="{{ map.get_image_url }}"  class="img-fluid mx-auto max-width:auto height:200px border border-white  mb-5" style="height:5em"> 
		</li></a>
                {% endfor %}
	</ul>                
        {% endif %}
</div>
{% endblock %}

clpsite/players/templates/players/player_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-flex justify-content-center bg-dark text-white mb-1">
<h1 class="display-1 h1 border-bottom mb-5">{{player.nick}}</h1>

</div>

<!-- Info de la Persona -->


<div class="d-inline mb-5 bg-white text-light mb-5 ">
<div class="d-flex bg-dark mb-4 ">

		<!-- Datos de la persona -->
		<div class="col-6 display-5 border-dark border text-center ">
			<p><strong> Nombre Completo:  </strong> {{player.fullname }}</p>
			<p><strong> Nacionalidad:  </strong>{{ player.country }}</p>
			<p><strong> Nacimiento:  </strong>{{ player.birthday }}</p>
			<p><strong> Horas jugadas:  </strong>{{ player.played_hours }}</p>
			<p><strong> Rank:  </strong>{{ player.rank }}</p>
		</div>

<!-- Fin Datos de la persona -->
<!-- Foto de perfil -->


		<div class="col-6 d-flex border border-dark ">
			<img src="{{ player.get_image_url }}"class="img-fluid mx-auto max-width:auto height:20em border border-white  mb-5"> 
		</div>

</div>
<!-- Fin Foto de perfil -->







<!-- Fin Info de la Persona-->
<!--  Historia del Player -->

<div class="d-flex justify-content-center bg-dark text-white mb-1">
<h1 class="display-1 h1 border-bottom mb-5">Historia</h1>

</div>


<div class="bg-dark mb-4">
	<div class="display-6 p-5  bg-dark text-light"> 
		<p class=""><strong>{{player.description}}.</strong></p>
	</div>

</div>

<!-- Fin Historia del Player -->
<!--  Pool de agentes  -->



<div class="d-flex justify-content-center bg-dark text-white mb-1">
<h1 class="display-1 h1 border-bottom mb-5 text-center">Pool de agentes</h1>

</div>

<div class="bg-dark">
	<ul class="row justify-content-center px-3 py-3">
	{% for agent in player.agents.all %}
                                <a  class=" col-sm-4 display-6 text-white text-center text-decoration-none mt-3" style="font-size: calc(1rem + 1vw)" href="{{agent.get_absolute_url}}" >
					<li class=" bg-dark text-center border " style="list-style-type: none; height: calcu(12rem + 1vw) ">
						<p class="px-3 "    > {{ agent.name }} </p>
				<img src="{{ agent.get_icon_url }}" class="img-fluid mx-auto max-width:auto height:200px border border-white  mb-5" style="height:5em"> 
                  </li></a>

	{% endfor %}
	</ul>
</div>






<!-- Fin Pool de agentes -->


<!-- Settings -->

<div class="d-flex justify-content-center bg-dark text-white mb-2">
	<h1 class="display-1 h1 border-bottom mb-5">Settings</h1>
</div>

<div class="d-inline display-6 justify-content-center text-center text-white mb-4">
	<div class="mb-5">
		<div class="border border-light bg-dark">
			{% if not player.sensivility is None %}
			        <p><strong> Sensivility:  </strong>{{player.sensivility}}</p>
			{% endif %}
			{% if not player.dpi is None %}
			        <p><strong> Dpi:  </strong>{{player.dpi}}</p>
			{% endif %}
			{% if not player.monitor is None %}
			        <p><strong> Monitor:  </strong>{{player.monitor}}</p>
			{% endif %}
			{% if not player.mouse is None %}
			        <p><strong> Mouse:  </strong>{{player.mouse}}</p>
			{% endif %}
		</div>
		<div class="border border-light bg-dark">
			{% if not player.mousepad is None %}
			        <p><strong> Mousepad:  </strong>{{player.mousepad}}</p>
			{% endif %}
			{% if not player.keyboard is None %}
			        <p><strong> Keyboard:  </strong>{{player.keyboard}}</p>
			{% endif %}
			{% if not player.headset is None %}
			        <p><strong> Headset:  </strong>{{player.headset}}</p>
			{% endif %}
			{% endblock %}

	
		</div>
	</div>
</div>
</div>

clpsite/players/templates/players/player_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="d-flex justify-content-center bg-dark text-white border mb-1">
<h1 class="display-1 h1 border-bottom mb-5">Players</h1>

</div>





<div class="bg-danger">
         {% if player_list %}
         <ul class="row justify-content-center ">
                {% for player in player_list %}

                                 <a  class=" col-sm-4 text-white text-center text-decoration-none mt-3" style="font-size: calc(1rem + 1vw)"  href="{{player.get_absolute_url}}">
					        
					 <li class=" bg-dark text-center border " style="list-style-type: none; height: calcu(12rem + 1vw) ">
					 <p class="px-3 "    > {{ player.nick }}</p>

					 <img src="{{ player.get_image_url }}" class="img-fluid mx-auto max-width:auto height:200px border border-white  mb-5" style="height:5em">
			
					 
                 
				 </li></a>
                 {% endfor %}    
         </ul>                      
         {% endif %}
</div>
 {% endblock %}

clpsite/players/templates/upload_image.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Upload Image</title>
  </head>
  <body>
    <form action="{% url 'players:upload_image' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
          <input id="id_image" type="file" accept="image/*" name="image" required>
      </p>
      <p>
          Image name:
          <input id="id_name" type="text" name="name" required>
      </p>
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>